server:
  port: 8080

spring:
  application:
    name: berlin

external:
  munich:
    base-url: http://localhost:9090

resilience4j:
  retry:
    instances:
      munich:
        max-attempts: 3
        wait-duration: 1s
